### ISSUE TITLE
Stop This

### ISSUE THREAD

**Issue by brotherlogic** [brotherlogic/githubcard#14]
panic: Post https://api.github.com/repos/brotherlogic/golisp/issues?access_token=0fb7c6685c8f720b460e6b0c571cfed0b330ef80: dial tcp: lookup api.github.com on 192.168.86.1:53: read udp 192.168.86.28:43100->192.168.86.1:53: i/o timeout

goroutine 1 [running]:
panic(0x3ce4c8, 0x1097c860)
	/usr/local/go/src/runtime/panic.go:500 +0x33c
main.(*GithubBridge).postURL(0x10843ebc, 0x10958740, 0x37, 0x1095b860, 0x4f, 0x0, 0x0)
	/home/simon/code/src/github.com/brotherlogic/githubcard/github.go:39 +0x2b0
main.(*GithubBridge).AddIssue(0x10843ebc, 0x40699e, 0xc, 0x1094e31e, 0x6, 0x1094a3c0, 0xe, 0x1094a3cf, 0xc)
	/home/simon/code/src/github.com/brotherlogic/githubcard/github.go:103 +0x29c
main.main()
	/home/simon/code/src/github.com/brotherlogic/githubcard/github.go:193 +0x7b0

**Comment by brotherlogic** [comment]
This has been stopped
